# Generated by Django 5.1.5 on 2025-01-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0013_alter_thirdpartymodelversion_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartymodelversion",
            name="provider",
            field=models.CharField(
                default="OPENAI",
                help_text="Deprecated in favor of model_provider_connection.provider",
                max_length=255,
            ),
        ),
    ]
