# Generated by Django 5.1.5 on 2025-01-22 23:05

from django.db import migrations, models
from pydantic import BaseModel
from enum import Enum

# copy data as it existed at the time of the migration
class ModelProviderConfig(BaseModel):
    litellm_slug: str


class ModelProviderChoices(Enum):
    OPENAI = ModelProviderConfig(litellm_slug="openai")
    AZURE_OPENAI = ModelProviderConfig(litellm_slug="azure")
    VERTEX_AI = ModelProviderConfig(litellm_slug="vertex_ai")
    CUSTOM = ModelProviderConfig(litellm_slug="openai")
    
provider_choices = [
   ('OpenAI', ModelProviderChoices.OPENAI.name),
   ('AzureOpenAI', ModelProviderChoices.AZURE_OPENAI.name),
   ('VertexAI', ModelProviderChoices.VERTEX_AI.name),
   ('Custom', ModelProviderChoices.CUSTOM.name),
]
# specify how to map data across the migration
def copy_provider_to_provider_choice(apps, schema_editor):
    ModelProviderConnection = apps.get_model('ml_model_providers', 'ModelProviderConnection')
    dct = {p[0]: p[1] for p in provider_choices}
    for connection in ModelProviderConnection.objects.all():
        try:
            connection.provider = dct[connection.provider]
            connection.save()
        except KeyError:
            pass
            

def copy_provider_choice_to_provider(apps, schema_editor):
    ModelProviderConnection = apps.get_model('ml_model_providers', 'ModelProviderConnection')
    dct = {p[1]: p[0] for p in provider_choices}
    for connection in ModelProviderConnection.objects.all():
        try:
            connection.provider = dct[connection.provider]
            connection.save()
        except KeyError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "ml_model_providers",
            "0006_modelproviderconnection_google_application_credentials_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelproviderconnection",
            name="provider",
            field=models.CharField(
                default="OPENAI",
                help_text="Model provider name",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            copy_provider_to_provider_choice,
            copy_provider_choice_to_provider
        ),
    ]
